export const biboCopy = {
  title: "Bibo · 你的个人 AI 搭档",
  space: "个人空间",
  conversation: "对话",
  sessionMissing: "这段对话不存在或已删除。请选择其他对话，或新建对话。",
  companion: "我的搭档",
  greeting: "嗨，我是 Bibo.",
  welcome: "从一件你正在做的事开始。我会认真听，也会尽力把它往前推进。",
  placeholder: "告诉 Bibo，你现在想做什么……",
  send: "发送消息",
  stop: "停止生成",
  savingHint: "回答保存后会出现在你的个人空间",
  copy: "复制回答",
  waiting: "正在思考…",
  copied: "已复制",
  copyFailed: "无法复制，请手动选择文字。",
  you: "你",
  backToLatest: "回到最新 ↓",
  login: "登录",
  register: "注册",
  email: "邮箱",
  password: "密码",
  code: "邮箱验证码",
  sendCode: "发送验证码",
  createAccount: "创建账号",
  accountIntro: "注册后，你的对话与个人空间会单独保存。先从一件真实的事开始。",
  busy: "Bibo 正在处理…",
  replying: "Bibo 正在回复…",
  saving: "正在保存这次对话…",
  interrupted: "上次生成中断，内容未保存。消息已放回输入框，可重新发送。",
  retry: "输入已保留，可重新发送。",
  resetConfirm: "确认清空 Bibo 的对话和个人空间？这项操作无法撤销。",
  resetDone: "个人空间已清空。你可以重新开始。",
  help: "使用说明与数据",
  logout: "退出登录",
  reset: "清空个人空间",
} as const;
