packages:
  - "apps/*"
  - "packages/*"
  - "packages/extensions/*"
  - "packages/ncp-packages/*"
  - "workers/*"
allowBuilds:
  electron: true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
