export const biboCopy = {
  title: "Bibo · 你的个人 AI 搭档",
  space: "个人空间",
  conversation: "对话",
  overview: "概览",
  overviewCompanion: "日常，多一个我。",
  inbox: "收件箱",
  calendar: "日程",
  tasks: "任务",
  endedTasks: "已结束",
  taskStatus: { planned: "待开始", active: "进行中", done: "已完成", cancelled: "已取消" },
  notes: "笔记",
  files: "文件",
  fileDirectory: "浏览目录",
  fileRoot: "个人空间",
  fileParent: "返回上级目录",
  fileEmptyDirectory: "文件夹为空",
  fileMore: "加载更多文件",
  fileDirectoryRetry: "重试读取目录",
  fileTabs: "打开的文件",
  fileWorkspaceTabs: "工作区文件",
  fileCloseWorkspace: "关闭工作区",
  fileSaved: "已保存",
  fileUnsaved: "未保存",
  fileSaving: "保存中…",
  fileSave: "保存",
  fileEdit: "编辑",
  filePreview: "预览",
  fileSource: "源码",
  fileConflict: "版本冲突 · 草稿已保留",
  fileSaveFailed: "保存失败 · 请重试",
  fileDraftProtected: "本标签页草稿已备份",
  fileDraftStorageFailed: "浏览器无法备份草稿，请保存后再刷新或离开。",
  markdownEditor: {
    toolbar: "Markdown 编辑工具", placeholder: "从这里开始写…",
    bold: "加粗（⌘/Ctrl+B）", italic: "斜体（⌘/Ctrl+I）", heading: "二级标题",
    list: "项目列表", code: "行内代码", search: "查找与替换（⌘/Ctrl+F）",
    undo: "撤销", redo: "重做", more: "更多格式",
    rich: {
      paragraph: "正文", heading: "标题", quote: "引用", divider: "分隔线", orderedList: "有序列表", taskList: "待办列表",
      link: "链接", image: "图片", table: "表格", codeBlock: "代码块", math: "公式", strike: "删除线",
      insert: "插入", text: "文本", advanced: "内容", url: "地址", confirm: "确认", upload: "上传", caption: "图片说明",
      language: "代码语言", noResults: "无匹配结果", copy: "复制", preview: "预览", hide: "收起", edit: "编辑",
      loading: "正在打开编辑器…", error: "暂时无法完成，请重试。", imageError: "请输入有效内容；图片地址需以 https:// 开头。", metadata: "文档属性",
      addRow: "在下方插入行", addColumn: "在右侧插入列", deleteRow: "删除当前行", deleteColumn: "删除当前列",
      find: "查找", replace: "替换", next: "下一个", previous: "上一个", replaceAll: "全部替换", close: "关闭",
    },
    phrases: { "Find": "查找", "Replace": "替换", "next": "下一个", "previous": "上一个", "all": "全部", "match case": "区分大小写", "by word": "全字匹配", "regexp": "正则表达式", "replace": "替换", "replace all": "全部替换", "close": "关闭", "No matches": "没有匹配结果" },
  },
  newConversation: "新对话",
  workspace: "打开右侧工作区",
  theme: "外观主题",
  classicTheme: "Bibo 经典",
  neutralTheme: "简约",
  sessionMissing: "这段对话不存在或已删除。请选择其他对话，或新建对话。",
  companion: "我的搭档",
  greeting: "嗨，我是 Bibo.",
  placeholder: "告诉 Bibo，你现在想做什么……",
  send: "发送消息",
  stop: "停止生成",
  copy: "复制回答",
  waiting: "正在思考…",
  questionLabel: "问题",
  questionOpen: "回答问题",
  questionClose: "关闭问题",
  questionPending: "待回答",
  questionAnswered: "已回答",
  questionSkipped: "已跳过",
  questionReference: "引用问题",
  questionRecommended: "推荐",
  questionCustom: "或自行填写回复",
  questionSkip: "跳过",
  questionSend: "发送",
  copied: "已复制",
  operationSaved: "操作已保存。",
  savedReadFailed: "操作已保存，视图暂未刷新。请重试读取。",
  taskSaved: (title: string) => `任务已保存：${title}`,
  taskDeleted: "任务已删除。",
  taskOutsideFilter: (title: string) => `已保存「${title}」，当前筛选下不显示。`,
  viewTask: "查看任务",
  taskToggled: (title: string, reopened: boolean) => `${reopened ? "已重新打开" : "已完成"}：${title}`,
  copyFailed: "无法复制，请手动选择文字。",
  you: "你",
  backToLatest: "回到最新",
  login: "登录",
  register: "注册",
  email: "邮箱",
  password: "密码",
  code: "邮箱验证码",
  createAccount: "创建账号",
  busy: "请稍候",
  retryFailed: "重试消息",
  interrupted: "上次生成中断，内容未保存。消息已放回输入框，可重新发送。",
  retry: "输入已保留，可重新发送。",
  resetConfirm: "确认清空 Bibo 的对话和个人空间？这项操作无法撤销。",
  resetDone: "个人空间已清空。你可以重新开始。",
  help: "使用说明与数据",
  logout: "退出登录",
  reset: "清空个人空间",
} as const;
