export const biboCopy = {
  resourceLoading: "正在打开详情",
  runIdle: "Bibo · 空闲", runWorking: "Bibo · 正在工作", runSaving: "Bibo · 正在保存结果",
  runStopping: "Bibo · 正在停止", runChecking: "Bibo · 正在查询状态", runReconnecting: "连接中断 · 正在重新连接", runOpen: "查看正在工作的会话",
  runToolWorking: "正在使用工具处理任务",
  recent: "最近",
  more: "更多",
  workspaceResize: "调整分栏宽度（方向键调整，双击或 Home 复位）",
  fileBody: "正文",
  today: "今天",
  yesterday: "昨天",
  title: "Bibo · 你的个人 AI 搭档",
  space: "个人空间",
  conversation: "对话",
  overview: "概览",
  overviewCompanion: "日常，多一个我。",
  inbox: "收件箱",
  inboxReadRetry: "重试标记已读",
  folderReference: "此引用指向目录，请在文件模块查看。",
  inboxBack: "← 全部消息",
  calendar: "日程",
  tasks: "任务",
  taskDetail: {
    editShort: "编辑", saveShort: "保存",
    properties: "编辑任务属性",
    title: "任务详情", close: "关闭任务详情", edit: "编辑任务", save: "保存任务", saving: "正在保存…",
    cancel: "取消", more: "更多任务操作", remove: "删除任务", deleteTitle: "删除任务？",
    deleteDescription: "任务及其子任务将被删除，此操作目前不可撤销。", deleting: "正在删除…",
    description: "说明", emptyDescription: "添加说明，记录背景、想法或完成标准…",
    subtasks: "子任务", emptySubtasks: "添加子任务", project: "项目", noProject: "未归入项目",
    start: "开始", due: "截止", priority: { high: "高优先级", medium: "中优先级", low: "低优先级" },
    draft: "未保存的修改", progress: (done: number, total: number) => `${done} / ${total}`,
  },
  endedTasks: "已结束",
  taskStatus: { planned: "待开始", active: "进行中", done: "已完成", cancelled: "已取消" },
  notes: "笔记",
  allNotes: "全部笔记",
  backToNotes: "返回全部笔记",
  newNote: "新笔记",
  untitledNote: "无标题笔记",
  noteNameUnavailable: "暂时无法创建新笔记，请稍后重试。",
  closeDocument: "关闭当前文档",
  fileMoveRename: "移动 / 重命名",
  fileDelete: "删除",
  searchNotes: "搜索笔记",
  search: "搜索",
  fileName: "名称",
  lastEdited: "上次编辑时间",
  files: "文件",
  fileDirectory: "浏览目录",
  fileRoot: "个人空间",
  fileParent: "返回上级目录",
  fileEmptyDirectory: "文件夹为空",
  fileMore: "加载更多文件",
  fileDirectoryRetry: "重试读取目录",
  fileDirectoryLoading: "正在读取目录",
  fileTabs: "打开的文件",
  fileWorkspaceTabs: "工作区文件",
  fileOpening: "正在打开…",
  fileSelect: "选择文档",
  fileOpenFailed: "打开失败",
  fileCloseWorkspace: "关闭工作区",
  fileSaved: "已保存",
  fileUnsaved: "未保存",
  fileSavePending: "等待自动保存…",
  fileOffline: "离线 · 草稿已保留，联网后自动保存",
  fileRetrySave: "重试保存",
  fileSaving: "保存中…",
  fileSave: "保存",
  fileEdit: "编辑",
  filePreview: "预览",
  fileDownload: "下载原文件",
  filePreviewReadOnly: "当前仅显示部分内容，请下载原文件查看；预览不能覆盖完整文件。",
  fileBinaryPreview: "此文件不支持文本预览，可下载原文件查看。",
  fileByteCount: "{count} 字节",
  fileSource: "源码",
  fileConflict: "版本冲突 · 草稿已保留",
  fileSaveFailed: "保存失败 · 草稿已保留",
  fileDraftProtected: "本标签页草稿已备份",
  fileDraftStorageFailed: "浏览器无法备份草稿，请保存后再刷新或离开。",
  markdownEditor: {
    toolbar: "Markdown 编辑工具", placeholder: "从这里开始写…",
    bold: "加粗（⌘/Ctrl+B）", italic: "斜体（⌘/Ctrl+I）", heading: "二级标题",
    list: "项目列表", code: "行内代码", search: "查找与替换（⌘/Ctrl+F）",
    undo: "撤销", redo: "重做", more: "更多格式",
    rich: {
      toggle: "折叠块", toggleContent: "展开或收起内容", callout: "提示块", underline: "下划线（⌘/Ctrl+U）", highlight: "高亮（⌘/Ctrl+Shift+H）", currentBlockActions: "当前块操作",
      paragraph: "正文", heading: "标题", quote: "引用", divider: "分隔线", orderedList: "有序列表", taskList: "待办列表",
      link: "链接", image: "图片", table: "表格", codeBlock: "代码块", math: "公式", strike: "删除线",
      insert: "插入", text: "文本", advanced: "内容", url: "地址", confirm: "确认", upload: "上传", caption: "图片说明",
      language: "代码语言", noResults: "无匹配结果", copy: "复制", preview: "预览", hide: "收起", edit: "编辑",
      mathHint: "Enter 换行，⌘/Ctrl + Enter 确认。多行对齐可使用 aligned。", mathExample: "多行示例", inlineMath: "行内公式", blockMath: "公式块",
      loading: "正在打开编辑器…", error: "暂时无法完成，请重试。", imageError: "请输入有效内容；图片地址需以 https:// 开头。", metadata: "文档属性",
      loadSlow: "编辑器加载较慢，请检查网络连接。", loadError: "编辑器未能加载，请检查网络连接后重试。", reload: "重新加载页面",
      addRow: "在下方插入行", addColumn: "在右侧插入列", deleteRow: "删除当前行", deleteColumn: "删除当前列",
      toggleHeaderRow: "切换标题行", toggleHeaderColumn: "切换标题列", alignLeft: "左对齐", alignCenter: "居中对齐", alignRight: "右对齐", mergeCells: "合并单元格", splitCell: "拆分单元格",
      moveRowUp: "向上移动行", moveRowDown: "向下移动行", moveColumnLeft: "向左移动列", moveColumnRight: "向右移动列",
      uploadingImage: "正在上传图片…",
      uploadContentChanged: "上传期间源码已修改，未插入图片。请回到编辑模式重新插入。",
      imageAlt: "替代文字", imageWidth: "宽度（像素）", imageAutoWidth: "自动适应", resizeImage: "调整图片宽度",
      commands: "插入内容", commandHint: "输入 / 插入内容", unlink: "取消链接", selectionTools: "文本格式", clearFormatting: "清除格式",
      appendRow: "新增一行", appendColumn: "新增一列", rowActions: "行操作", columnActions: "列操作", addRowBefore: "在上方插入行", addColumnBefore: "在左侧插入列",
      commandNavigate: "选择", commandDescriptions: { paragraph: "普通文本段落", h1: "大标题", h2: "章节标题", h3: "小节标题", list: "简洁的项目列表", orderedList: "有先后顺序的步骤", taskList: "可勾选的待办事项", quote: "突出一段引用", toggle: "用标题展开或收起一组内容", callout: "醒目地展示提示或说明", table: "用行列组织内容", codeBlock: "带语法高亮的代码", math: "独占一块，可编辑多行公式", inlineMath: "嵌入文字，与正文同行显示", image: "上传或通过链接插入图片", link: "链接到网页或文档", divider: "分隔两个内容区域" },
      deleteBlock: "删除", turnInto: "转换成",
      blockActions: "块操作", searchBlockActions: "搜索操作…", duplicateBlock: "创建副本", insertBeforeBlock: "在上方插入", insertAfterBlock: "在下方插入", copyCode: "拷贝代码",
      blockNames: { paragraph: "文本", heading: "标题", codeBlock: "代码", table: "表格", image: "图片", blockMath: "公式", bulletList: "项目列表", orderedList: "有序列表", taskList: "待办列表", listItem: "列表项", taskItem: "待办项", blockquote: "引用", details: "折叠块", detailsSummary: "折叠标题", detailsContent: "折叠内容", horizontalRule: "分隔线" },
      find: "查找", replace: "替换", next: "下一个", previous: "上一个", replaceAll: "全部替换", close: "关闭",
    },
    phrases: { "Find": "查找", "Replace": "替换", "next": "下一个", "previous": "上一个", "all": "全部", "match case": "区分大小写", "by word": "全字匹配", "regexp": "正则表达式", "replace": "替换", "replace all": "全部替换", "close": "关闭", "No matches": "没有匹配结果" },
  },
  documentView: { title: "目录与排版", outline: "文档目录", empty: "添加标题后，可在这里快速定位章节。", untitled: "未命名标题", width: "页面宽度", font: "文字大小", standard: "标准", wide: "全宽", small: "小号", characters: "正文约 {count} 个字符（不含空格）" },
  newConversation: "新对话",
  createConversation: "新建会话",
  workspace: "打开右侧工作区",
  theme: "外观主题",
  classicTheme: "Bibo 经典",
  neutralTheme: "简约",
  sessionMissing: "这段对话不存在或已删除。请选择其他对话，或新建对话。",
  companion: "我的搭档",
  greeting: "嗨，我是 Bibo.",
  placeholder: "告诉 Bibo，你现在想做什么……",
  send: "发送消息",
  stop: "停止生成",
  copy: "复制回答",
  waiting: "正在思考…",
  questionLabel: "问题",
  questionOpen: "回答问题",
  questionClose: "关闭问题",
  questionPending: "待回答",
  questionAnswered: "已回答",
  questionSkipped: "已跳过",
  questionReference: "引用问题",
  questionRecommended: "推荐",
  questionCustom: "或自行填写回复",
  questionSkip: "跳过",
  questionSend: "发送",
  copied: "已复制",
  operationSaved: "操作已保存。",
  savedReadFailed: "操作已保存，视图暂未刷新。请重试读取。",
  taskSaved: (title: string) => `任务已保存：${title}`,
  taskDeleted: "任务已删除。",
  taskOutsideFilter: (title: string) => `已保存「${title}」，当前筛选下不显示。`,
  viewTask: "查看任务",
  taskToggled: (title: string, reopened: boolean) => `${reopened ? "已重新打开" : "已完成"}：${title}`,
  copyFailed: "无法复制，请手动选择文字。",
  you: "你",
  backToLatest: "回到最新",
  login: "登录",
  register: "注册",
  email: "邮箱",
  password: "密码",
  code: "邮箱验证码",
  createAccount: "创建账号",
  busy: "请稍候",
  retryFailed: "重试消息",
  retry: "输入已保留，可重新发送。",
  resetConfirm: "确认清空 Bibo 的对话和个人空间？这项操作无法撤销。",
  resetDone: "个人空间已清空。你可以重新开始。",
  help: "使用说明与数据",
  logout: "退出登录",
  reset: "清空个人空间",
} as const;
