export const biboCopy = {
  title: "Bibo · 你的个人 AI 搭档",
  space: "个人空间",
  conversation: "对话",
  overview: "概览",
  inbox: "收件箱",
  calendar: "日程",
  tasks: "任务",
  notes: "笔记",
  files: "文件",
  newConversation: "新对话",
  workspace: "打开右侧工作区",
  theme: "外观主题",
  classicTheme: "Bibo 经典",
  neutralTheme: "简约",
  sessionMissing: "这段对话不存在或已删除。请选择其他对话，或新建对话。",
  companion: "我的搭档",
  greeting: "嗨，我是 Bibo.",
  placeholder: "告诉 Bibo，你现在想做什么……",
  send: "发送消息",
  stop: "停止生成",
  copy: "复制回答",
  waiting: "正在思考…",
  copied: "已复制",
  operationSaved: "操作已保存。",
  savedReadFailed: "操作已保存，视图暂未刷新。请重试读取。",
  taskSaved: (title: string) => `任务已保存：${title}`,
  taskDeleted: "任务已删除。",
  taskOutsideFilter: (title: string) => `已保存「${title}」，当前筛选下不显示。`,
  viewTask: "查看任务",
  taskToggled: (title: string, reopened: boolean) => `${reopened ? "已重新打开" : "已完成"}：${title}`,
  copyFailed: "无法复制，请手动选择文字。",
  you: "你",
  backToLatest: "回到最新",
  login: "登录",
  register: "注册",
  email: "邮箱",
  password: "密码",
  code: "邮箱验证码",
  sendCode: "发送验证码",
  createAccount: "创建账号",
  accountIntro: "注册后，你的对话与个人空间会单独保存。先从一件真实的事开始。",
  busy: "请稍候",
  retryFailed: "重试消息",
  interrupted: "上次生成中断，内容未保存。消息已放回输入框，可重新发送。",
  retry: "输入已保留，可重新发送。",
  resetConfirm: "确认清空 Bibo 的对话和个人空间？这项操作无法撤销。",
  resetDone: "个人空间已清空。你可以重新开始。",
  help: "使用说明与数据",
  logout: "退出登录",
  reset: "清空个人空间",
} as const;
