export const PACKAGED_RUNTIME_HOME_OVERRIDE_ENV = "NEXTCLAW_DESKTOP_RUNTIME_HOME_OVERRIDE";
export const PACKAGED_DESKTOP_DATA_OVERRIDE_ENV = "NEXTCLAW_DESKTOP_DATA_DIR_OVERRIDE";

// Keep the launcher's process-boundary protocol local and dependency-free. Importing
// the kernel package here would evaluate its full root entry before Electron can
// initialize the desktop logger or window.
export const RUNTIME_INSTANCE_DISTRIBUTION_ENV = "NEXTCLAW_RUNTIME_DISTRIBUTION";
export const RUNTIME_INSTANCE_INSTALLATION_KIND_ENV = "NEXTCLAW_DESKTOP_INSTALLATION_KIND";
export const RUNTIME_INSTANCE_PORTABLE_DATA_ROOT_ENV = "NEXTCLAW_DESKTOP_PORTABLE_DATA_ROOT";
export const RUNTIME_INSTANCE_DESKTOP_DATA_DIRECTORY_ENV = "NEXTCLAW_DESKTOP_DATA_DIRECTORY";
export const RUNTIME_INSTANCE_DESKTOP_LOGS_DIRECTORY_ENV = "NEXTCLAW_DESKTOP_LOGS_DIRECTORY";
