/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 8346e1976ba799d463b8788e8f824234)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/app/bibo-hosted.app");
		durableNamespaces: "BiboUserContainer" | "BiboModelBudget" | "Sandbox";
	}
	interface Env {
		SNAPSHOTS: R2Bucket;
		ASSETS: Fetcher;
		BIBO_USER: DurableObjectNamespace<import("./src/app/bibo-hosted.app").BiboUserContainer>;
		BIBO_MODEL_BUDGET: DurableObjectNamespace<import("./src/app/bibo-hosted.app").BiboModelBudget>;
		BIBO_SANDBOX: DurableObjectNamespace<import("./src/app/bibo-hosted.app").Sandbox>;
	}
}
interface Env extends Cloudflare.Env { BIBO_DEEPSEEK_API_KEY: string; BIBO_EXA_API_KEY?: string; BIBO_EDGE_ADMIN_TOKEN?: string }
