/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: f92d275b422f1a490cf8333afc44ec0b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/app/bibo-hosted.app");
		durableNamespaces: "BiboUserContainer" | "BiboModelBudget";
	}
	interface Env {
		SNAPSHOTS: R2Bucket;
		ASSETS: Fetcher;
		BIBO_USER: DurableObjectNamespace<import("./src/app/bibo-hosted.app").BiboUserContainer>;
		BIBO_MODEL_BUDGET: DurableObjectNamespace<import("./src/app/bibo-hosted.app").BiboModelBudget>;
	}
}
interface Env extends Cloudflare.Env { BIBO_DEEPSEEK_API_KEY: string }
