export const FIELD_HELP: Record<string, string> = {
  "agents.defaults.workspace": "Workspace directory for agent context files and memory.",
  "agents.defaults.model": "Default model identifier used by the agent. Examples: minimax/MiniMax-M2.5 · minimax/MiniMax-M2.1 · openrouter/anthropic/claude-3.5-sonnet · openrouter/openai/gpt-4o-mini.",
  "agents.defaults.maxTokens": "Maximum tokens per response.",
  "agents.defaults.maxToolIterations": "Maximum tool calls per turn.",
  "agents.context.bootstrap.files": "Files injected into the system prompt at startup.",
  "agents.context.bootstrap.minimalFiles": "Minimal file set used for low-context runs.",
  "agents.context.bootstrap.heartbeatFiles": "Files checked periodically for tasks.",
  "agents.context.bootstrap.perFileChars": "Max chars per bootstrap file.",
  "agents.context.bootstrap.totalChars": "Max total chars across bootstrap files.",
  "agents.context.memory.enabled": "Enable memory injection from memory files.",
  "agents.context.memory.maxChars": "Max characters of memory injected per turn.",
  "providers.*": "Configure credentials and endpoints for this provider.",
  "providers.openai": "Leading AI models including GPT-4 and GPT-3.5.",
  "providers.*.apiKey": "API key for this provider.",
  "providers.minimax.apiBase": "China: https://api.minimaxi.com/v1. Overseas: https://api.minimax.io/v1. Pick the base URL that matches your account region.",
  "providers.*.apiBase": "Override the provider API base URL if needed.",
  "providers.*.extraHeaders": "Extra headers to send to the provider.",
  "providers.*.wireApi": "Select API mode (auto/chat/responses) for providers that support it.",
  "gateway.host": "Bind address for the gateway server.",
  "gateway.port": "Port for the gateway server.",
  "ui.enabled": "Enable the built-in UI server.",
  "ui.host": "UI host is runtime-managed and treated as read-only (always 0.0.0.0 on CLI start/restart/serve/ui/gateway).",
  "ui.port": "Port for the UI server.",
  "ui.open": "Open the browser when UI starts.",
  "tools.web.search.apiKey": "API key for the configured web search provider.",
  "tools.web.search.maxResults": "Default number of search results.",
  "tools.exec.timeout": "Command execution timeout (seconds).",
  "tools.restrictToWorkspace": "Restrict tools to the workspace directory.",
  "plugins.enabled": "Enable plugin/extension loading.",
  "plugins.allow": "Optional allowlist of plugin ids; when set, only listed plugins load.",
  "plugins.deny": "Optional denylist of plugin ids; denylist takes precedence.",
  "plugins.load.paths": "Additional plugin files or directories to load.",
  "plugins.entries": "Per-plugin settings keyed by plugin id.",
  "plugins.entries.*.enabled": "Override plugin enable/disable for this plugin.",
  "plugins.entries.*.config": "Plugin-defined config payload validated by plugin schema.",
  "plugins.installs": "CLI-managed install metadata.",
  "plugins.installs.*.source": "Install source (npm, archive, or path).",
  "plugins.installs.*.spec": "Original npm spec used for installation.",
  "plugins.installs.*.sourcePath": "Original archive/path used for installation.",
  "plugins.installs.*.installPath": "Resolved local install path.",
  "plugins.installs.*.version": "Version recorded at install time.",
  "plugins.installs.*.installedAt": "ISO timestamp of last install/update.",
  "channels.*": "Configure connection and credentials for this channel.",
  "channels.telegram": "Connect with Telegram bots for instant messaging.",
  "channels.slack": "Integrate with Slack workspaces for team collaboration.",
  "channels.email": "Send and receive messages via email protocols.",
  "channels.webhook": "Receive HTTP webhooks for custom integrations.",
  "channels.discord": "Connect Discord bots to your community servers.",
  "channels.feishu": "Enterprise messaging and collaboration platform.",
  "channels.whatsapp.bridgeUrl": "WebSocket URL for the WhatsApp bridge.",
  "channels.telegram.token": "Telegram bot token.",
  "channels.telegram.proxy": "Optional HTTP proxy for Telegram.",
  "channels.discord.token": "Discord bot token.",
  "channels.discord.allowBots": "Allow bot-authored messages to trigger replies (default: false).",
  "channels.discord.gatewayUrl": "Override Discord gateway URL.",
  "channels.discord.intents": "Gateway intents bitmask.",
  "channels.discord.proxy": "Optional HTTP(S) proxy for Discord attachment downloads.",
  "channels.discord.mediaMaxMb": "Maximum inbound Discord attachment size in MB.",
  "channels.feishu.appId": "Feishu app ID.",
  "channels.feishu.appSecret": "Feishu app secret.",
  "channels.feishu.encryptKey": "Feishu encrypt key (if enabled).",
  "channels.feishu.verificationToken": "Feishu verification token.",
  "channels.dingtalk.clientId": "DingTalk client ID.",
  "channels.dingtalk.clientSecret": "DingTalk client secret.",
  "channels.mochat.baseUrl": "Base URL for Mochat API.",
  "channels.mochat.socketUrl": "WebSocket URL for Mochat (optional override).",
  "channels.mochat.socketPath": "Socket.IO path for Mochat.",
  "channels.mochat.clawToken": "Mochat claw token.",
  "channels.mochat.agentUserId": "Mochat agent user id.",
  "channels.mochat.replyDelayMode": "Reply delay policy for Mochat.",
  "channels.mochat.replyDelayMs": "Reply delay duration in milliseconds.",
  "channels.slack.mode": "Slack connection mode (socket or webhook).",
  "channels.slack.webhookPath": "Slack webhook path when using webhook mode.",
  "channels.slack.botToken": "Slack bot token.",
  "channels.slack.appToken": "Slack app-level token.",
  "channels.slack.allowBots": "Allow bot-authored messages to trigger replies (default: false).",
  "channels.slack.groupPolicy": "Group policy for Slack channels.",
  "channels.slack.dm.policy": "DM policy for Slack.",
  "channels.email.imapHost": "IMAP server host.",
  "channels.email.imapPort": "IMAP server port.",
  "channels.email.imapUsername": "IMAP username.",
  "channels.email.imapPassword": "IMAP password.",
  "channels.email.smtpHost": "SMTP server host.",
  "channels.email.smtpPort": "SMTP server port.",
  "channels.email.smtpUsername": "SMTP username.",
  "channels.email.smtpPassword": "SMTP password.",
  "channels.email.fromAddress": "Default From address for outgoing mail.",
  "channels.email.pollIntervalSeconds": "Polling interval in seconds.",
  "channels.email.maxBodyChars": "Max chars to read from incoming emails.",
  "channels.email.subjectPrefix": "Prefix used for reply subjects.",
  "channels.qq.appId": "QQ app ID.",
  "channels.qq.secret": "QQ app secret."
};
