export { NextClawExtension } from "./services/extension-client.service.js";
export type {
  ChannelConfigGetRequest,
  ChannelConfigGetResponse,
  ChannelFileContent,
  ChannelImageContent,
  ChannelMessageContent,
  ChannelSubmittedMessage,
  ChannelSubmittedAttachment,
  ChannelTextContent,
  ExtensionCapabilities,
  ExtensionCapabilityHandler,
  ExtensionCapabilityPayload,
  ExtensionChannel,
  ExtensionChannelConfig,
  ExtensionChannels,
  ExtensionRequest,
  ExtensionRequestHandler,
  ExtensionRequestResponse,
  ExtensionTransportEnvelope,
  NextClawExtensionOptions,
  NextClawExtensionWebSocketLike,
} from "./types/extension-sdk.types.js";
